apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: bakveientilarbeid
  namespace: paw
  labels:
    team: paw
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /bakveientilarbeid/internal/isAlive
    initialDelay: 10
  readiness:
    path: /bakveientilarbeid/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  webproxy: true
  ingresses:
    - "https://www.nav.no/bakveientilarbeid"
    - "https://bakveientilarbeid.intern.nav.no/bakveientilarbeid"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "500m"
      memory: 580Mi
