apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: bakveientilarbeid
  namespace: paw
  labels:
    team: paw
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /bakveientilarbeid/internal/isAlive
    initialDelay: 10
  readiness:
    path: /bakveientilarbeid/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  tokenx:
    enabled: true
  webproxy: true
  ingresses:
    - "https://dev.nav.no/bakveientilarbeid"
    - "https://bakveientilarbeid.dev.intern.nav.no/bakveientilarbeid"
  envFrom:
    - configmap: loginservice-idporten
  env:
    - name: CORS_ALLOWED_ORIGINS
      value: dev.nav.no
    - name: CORS_ALLOWED_SCHEMES
      value: https
    - name: MELDEKORT_APP_NAME
      value: "meldekort-api-q1"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "500m"
      memory: 580Mi
  accessPolicy:
    inbound:
      rules:
        - application: veientilarbeid
    outbound:
      rules:
        - application: dp-innsyn
          namespace: teamdagpenger
        - application: meldekort-api-q1
          namespace: meldekort
